config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  devise_for :users
  resources :seminar_projects do
    member do
      post :determine
    end
  end
  resources :entries, only: %i(create destroy)
  resources :comments, only: %i(create destroy)
  resources :seminar_sessions
  resources :preparations
  get 'seminar_sessions/:id/download/:type' => 'seminar_sessions#download', as: 'seminar_session_download'
  get 'preparations/:id/list/' => 'preparations#edit_list', as: 'edit_preparation_list'
  post 'preparations/:id/list/' => 'preparations#update_list', as: 'update_preparation_list'
end

app/models/seminar_session.rb
# == Schema Information
#
# Table name: seminar_sessions
#
#  id                 :integer          not null, primary key
#  user_id            :integer
#  seminar_project_id :integer          not null
#  date               :datetime
#  help               :boolean          default(FALSE), not null
#  end                :boolean          default(FALSE), not null
#  created_at         :datetime
#  updated_at         :datetime
#  title              :text
#  slide              :string(255)
#  resume             :string(255)
#  answer             :string(255)
#  slide_status_json  :text
#  resume_status_json :text
#  answer_status_json :text
#

class SeminarSession < ActiveRecord::Base
  mount_uploader :slide, DocumentUploader
  mount_uploader :resume, DocumentUploader
  mount_uploader :answer, DocumentUploader
  has_one :preparation
  belongs_to :seminar_project
  belongs_to :presenter, foreign_key: :user_id, class_name: User
  has_many :seminar_sessions

  def prepare_preparation
    return preparation if preparation
    prep = build_preparation
    prep.book = { seminar_project.books.first.name => false }
    prep.read = { '0章0節' => false }
    prep.note = { '0章0節' => false }
    prep.material = { '章構成' => false, 'レイアウト' => false, '図解' => false }
    prep
  end

  def prepare_preparation!
    prepare_preparation.save!
  end

  def presenter?(user)
    return true if presenter == user
    false
  end

  def document(type)
    return nil unless %w(slide resume answer).index(type)
    return slide if type == 'slide'
    return resume if type == 'resume'
    return answer if type == 'answer'
    nil
  end

  def create
    super
    preparation = prepare_preparation
    preparation.save!
  end

  def comments
    Comment.where(target: Comment::Target::SESSION, target_id: id)
  end
end

app/controllers/seminar_sessions_controller.rb
class SeminarSessionsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_project, :load_session

  def show
  end

  def edit
  end

  def create
    @seminar_project.seminar_sessions.create
    redirect_to seminar_project_path(@seminar_project)
  end

  def update
    @seminar_session.update(session_params)
    store_pages!('slide')
    redirect_to seminar_project_path(@seminar_session.seminar_project)
  end

  def download
    send_file(@seminar_session.resume.path) if params[:type] == 'resume'
  end

  private

  def session_params
    params.require(:seminar_session).permit(
      :seminar_project_id, :date, :user_id, :help,
      :title, :slide, :resume, :answer
    )
  end

  def load_project
    @seminar_project = SeminarProject.find(params[:seminar_project_id]) unless params[:seminar_project_id].blank?
  end

  def load_session
    @seminar_session = SeminarSession.find(params[:id]) unless params[:id].blank?
    @seminar_session.prepare_preparation! if @seminar_session
  end

  def store_pages!(type)
    file = @seminar_session.document(type)
    return if file.blank?

    extracted = false
    mime = FileMagic.new(FileMagic::MAGIC_MIME_TYPE).file(file.current_path)
    office_extension = file.current_path.match(/(ppt|pptx|doc|docx|xls|xlsx)$/)
    if ['application/zip', 'application/vnd.ms-excel', 'application/vnd.ms-office', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.ms-word.document.macroEnabled.12', 'application/vnd.openxmlformats-officedocument.wordprocessingml.template', 'application/vnd.ms-word.template.macroEnabled.12', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel.sheet.macroEnabled.12', 'application/vnd.openxmlformats-officedocument.spreadsheetml.template', 'application/vnd.ms-excel.template.macroEnabled.12', 'application/vnd.ms-excel.sheet.binary.macroEnabled.12', 'application/vnd.ms-excel.addin.macroEnabled.12', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.ms-powerpoint.presentation.macroEnabled.12', 'application/vnd.openxmlformats-officedocument.presentationml.slideshow', 'application/vnd.ms-powerpoint.slideshow.macroEnabled.12', 'application/vnd.openxmlformats-officedocument.presentationml.template', 'application/vnd.ms-powerpoint.template.macroEnabled.12'].index(mime) && office_extension
      extracted = true
      office_extension = office_extension[0].gsub(/x$/, '')
      tempfile = Tempfile.new(['temp', '.' + office_extension])
      tempfile_pdf_path = tempfile.path.gsub(/\.#{office_extension}$/, '.pdf')
      begin
        tempfile.binmode
        tempfile.write file.read
        tempfile.close
        generate_thumbnails(type, tempfile.path, tempfile_pdf_path)

        begin
          File.unlink(tempfile_pdf_path) if File.exist?(tempfile_pdf_path)
        rescue
        end
      ensure
        tempfile.unlink
      end
    elsif mime == 'application/pdf'
      extracted = true
      dir_prefix = "public/uploads/seminar_session/#{type}/#{@seminar_session.id}/pages"
      generate_large_thumbnails(file.current_path, dir_prefix)
      generate_medium_thumbnails(file.current_path, dir_prefix)
      generate_small_thumbnails(file.current_path, dir_prefix)
    end

    return unless extracted

    store_files_status(type)
    @seminar_session.save
  end

  def generate_thumbnails(type, file_path, pdf_path)
    dir_prefix = "public/uploads/seminar_session/#{type}/#{@seminar_session.id}/pages"
    return if Dir.exist?(dir_prefix) && Dir.exist?(dir_prefix + '-m') && Dir.exist?(dir_prefix + '-s')

    logger.debug "Convert to pdf: #{pdf_path}"
    `unoconv -f pdf -T 60 "#{file_path}"`
    generate_large_thumbnails(pdf_path, dir_prefix)
    generate_medium_thumbnails(pdf_path, dir_prefix)
    generate_small_thumbnails(pdf_path, dir_prefix)
  end

  def generate_large_thumbnails(pdf_path, dir_prefix)
    FileUtils.rm_rf(dir_prefix) if Dir.exist?(dir_prefix)
    Dir.mkdir(dir_prefix, 0755)
    logger.debug 'Generate thumbnails'
    `convert -density 300 "#{pdf_path}" #{Rails.root}/#{dir_prefix}/%03d.png`
  end

  def generate_medium_thumbnails(pdf_path, dir_prefix)
    FileUtils.rm_rf(dir_prefix + '-m') if Dir.exist?(dir_prefix + '-m')
    Dir.mkdir("#{dir_prefix}-m", 0755)
    logger.debug 'Generate medium thumbnails'
    `convert -density 75 "#{pdf_path}" #{Rails.root}/#{dir_prefix}-m/%03d.png`
  end

  def generate_small_thumbnails(pdf_path, dir_prefix)
    FileUtils.rm_rf(dir_prefix + '-s') if Dir.exist?(dir_prefix + '-s')
    Dir.mkdir("#{dir_prefix}-s", 0755)
    logger.debug 'Generate small thumbnails'
    `convert -resize 240x "#{pdf_path}" #{Rails.root}/#{dir_prefix}-s/%03d.png`
  end

  def store_files_status(type)
    files = Dir.glob("#{Rails.root}/public/uploads/seminar_session/#{type}/#{@seminar_session.id}/pages/*").sort
    files.map! do |file_path|
      File.basename(file_path)
    end
    files_status = {}
    files.each do |file_name|
      files_status[file_name] = 'open'
    end
    @seminar_session.slide_status_json = JSON.generate(files_status)
  end
end

app/views/seminar_sessions/_list.html.slim
h2 セッション一覧
= button_to '追加', seminar_sessions_path, class: 'btn btn-primary', params: { seminar_project_id: @seminar_project.id }
- @seminar_project.seminar_sessions.order(:date).each.with_index(1) do |s, i|
  - s.prepare_preparation!
  .panel.panel-info
    .panel-heading = "第#{i}回 [#{s.decorate.title}]"
    .panel-body
      table.table
        tr
          th 発表者
          td = s.decorate.presenter
        tr
          th 日程
          td = s.decorate.date
        tr
          td[colspan="2"]
            .div
              .btn-group
                = link_to '準備状況', preparation_path(id: s.preparation.id), class: 'btn btn-primary'
                = link_to 'セッション開始', seminar_session_path(s), class: 'btn btn-info'
        - if @seminar_project.owner?(current_user) || s.presenter?(current_user)
          tr
            td.conpact-cell
              = link_to '編集', edit_seminar_session_path(s), class: 'btn btn-primary'
            - if @seminar_project.owner?(current_user)
              td
                = modal_toggle '発表者選択', dialog: "#presenterModal#{s.id}", class: 'btn btn-warning'
                = render 'seminar_sessions/presenter_modal', seminar_session: s

      #accordion.panel-group[role="tablist" aria-multiselectable="true"]
        .panel.panel-default
          #headingOne.panel-heading[role="tab"]
            h4.panel-title
              a[role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne"]
                |  コメント
          #collapseOne.panel-collapse.collapse[role="tabpanel" aria-labelledby="headingOne"]
            .panel-body
              = form_for @session_comment, html: { class: "form-inline" } do |f|
                = f.hidden_field :target, value: Comment::Target::SESSION
                = f.hidden_field :target_id, value: s.id
                .form-group
                  = f.text_field :content, class: "form-control comment-form"
                = f.submit "投稿", class: "btn btn-default"
              table.table
                - s.comments.each do |c|
                  - c = c.decorate
                  tr
                    th.conpact-cell = c.user.nick_name + " >"
                    td = c.session_comment

app/views/seminar_sessions/_presenter_modal.html.slim
= form_for seminar_session do |f|
  -modal_body = capture do
    p 発表者を選択してください
    .form-group
      = f.collection_select :user_id, User.all, :id, :real_name, include_blank: ""
  = modal_dialog id: "presenterModal#{seminar_session.id}",
    header: {show_close: true, title: '発表者選択'},
    body: modal_body,
    footer: submit_tag('確定する', class: "btn btn-primary") + content_tag(:button, 'キャンセル', 'data-dismiss' => 'modal', class: "btn btn-default")

app/views/seminar_sessions/edit.html.slim
h1 セッション編集

= form_for @seminar_session do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :date
    = f.text_field :date, class: 'form-control datetimepicker'
  - if @seminar_session.presenter?(current_user)
    .form-group
      = f.label :slide
      = f.file_field :slide
    .form-group
      = f.label :resume
      = f.file_field :resume
    .form-group
      = f.label :answer
      = f.file_field :answer
  = f.submit '更新', class: 'btn btn-primary'

javascript:
  $('.datetimepicker').datetimepicker();

app/views/seminar_sessions/show.html.slim
.seminar-session-container
  h1 講義支援

  h2 = @seminar_session.title

  .session-container
    .infobar
      span
        | ここにお知らせ等が表示されます。
    .comment-input-container
      textarea placeholder="コメントを入力してください。"
      a.btn-send-comment 送信する
      a.btn-cancel-comment やめる
    .slide-container
      .slide
        - slides = JSON.parse(@seminar_session.slide_status_json)
        - image_path = File.dirname(@seminar_session.slide.url)
        - i = 0
        - slides.keys.each do |file|
          = image_tag image_path + '/pages/' + file, 'data-slide-no' => i, class: (i == 0 ? '' : 'hide')
          - i += 1
        a.btn-slide-next
          = image_tag 'slide-next.png'
        a.btn-slide-prev
          = image_tag 'slide-next.png'
        .slide-info
          | 1/#{ @seminar_session.decorate.slide_status.count }
      .slide-controller
        .btn.btn-xs 理解
        .btn.btn-xs 同期の停止
        .btn.btn-xs#btn-toggle-comment-input コメントする
        .btn.btn-xs#btn-toggle-comment コメントを隠す

      .comment-container
        .tab
          a.tab-btn.active data-target="comment" コメント
          a.tab-btn data-target="member" 参加者
        ul.comment
          li 
            .comment-info
              span.id 001
              span.name 
                | [川鯉]
            span.content 思考を習うチャンスもう少し解説がわかりやすかったかもね
          li
            .comment-info
              span.id 002
              span.name 
                | [豊田]
            span.content 
              | > 多様性なら、ここで勉強したのが分かりやすかったです。参考までに。 http://homepage1.nifty.com/Cavhogehogehogehogehoge/hogehogehoge/hogehoge
          li
            .comment-info
              span.id 003
              span.name 
                | [青木] 
            span.content 
              | > 説明少なくて、すみません。ここ見たら詳しい説明が。 http://cran.r-project.org/doc/contrib/manuals-jp/R-lang.jp v110.pdf
          li
            .comment-info
              span.id 004
              span.name 
                | [熊野]
            span.content
              | > ありがとうございます。
        ul.member
          - WebsocketRails['session' + @seminar_session.id.to_s].subscribers.each do |con|
            - user = User.find(con.user_identifier)
            li data-user-id=(user.id) class=(@seminar_session.user_id == user.id ? 'presentator' : '')
              = user.decorate.name_with_student_code

    .memo-container
      textarea
        | 個人ノート:
        


input type="hidden" name="session_id" value=( @seminar_session.id )

coffee:
  syncSessionClass.enterSession($('input[name=session_id]').val())
  $('.tab-btn').on('click', ->
    if $(this).attr('data-target') == 'member'
      $('ul.member').show()
      $('ul.comment').hide()
    else
      $('ul.member').hide()
      $('ul.comment').show()
    $('.tab-btn.active').removeClass('active')
    $(this).addClass('active')
  )
  $(window).on('onbeforeunload page:before-change', ->
    syncSessionClass.leave()
    $(window).unbind('onbeforeunload page:before-change')
  )
  $('#btn-toggle-comment').on('click', ->
    toggleCommentList($('.comment-container').css('x') == '100%')
  )
  $('#btn-toggle-comment-input').on('click', ->
    toggleCommentInput($('.comment-input-container').css('height') == '0px')
  )
  $('.btn-slide-next').on('click', @slideToNext)
  $('.btn-slide-prev').on('click', @slideToPrev)