config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  devise_for :users
  resources :seminar_projects do
    member do
      post :determine
    end
  end
  resources :entries, only: %i(create destroy)
  resources :comments, only: %i(create destroy)
  resources :seminar_sessions
  resources :preparations
  get 'seminar_sessions/:id/download/:type' => 'seminar_sessions#download', as: 'seminar_session_download'
  get 'preparations/:id/list/' => 'preparations#edit_list', as: 'edit_preparation_list'
  post 'preparations/:id/list/' => 'preparations#update_list', as: 'update_preparation_list'
end

app/models/preparation.rb
# == Schema Information
#
# Table name: preparations
#
#  id                 :integer          not null, primary key
#  seminar_session_id :integer          not null
#  book               :string(255)      not null
#  read               :string(255)      not null
#  note               :string(255)      not null
#  material           :string(255)      not null
#  practice           :integer          default(0), not null
#  created_at         :datetime
#  updated_at         :datetime
#

class Preparation < ActiveRecord::Base
  belongs_to :seminar_session

  serialize :book
  serialize :read
  serialize :note
  serialize :material

  def prep_list
    { 'book' => book, 'read' => read, 'note' => note, 'material' => material }
  end
end

app/controllers/preparations_controller.rb
class PreparationsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_preparation

  def show
  end

  def update
    @preparation.practice = params['preparation']['practice']
    @preparation.update(update_params)
    redirect_to preparation_path(@preparation)
  end

  def update_list
    @preparation.update(update_list_params)
    redirect_to preparation_path(@preparation)
  end

  private

  def load_preparation
    @preparation = Preparation.find(params[:id]) unless params[:id].blank?
  end

  def preparation_params
    p = {}
    %w(book read note material).each do |key|
      p.store(key, params[key]) unless params[key].blank?
    end
    p
  end

  def update_params
    list = @preparation.prep_list
    list.each do |column, value|
      value.keys.each do |item|
        list[column][item] = !(preparation_params[column].nil? || preparation_params[column][item].nil?)
      end
    end
  end

  def update_list_params
    list = { 'book' => {}, 'read' => {}, 'note' => {}, 'material' => {} }
    preparation_params.each do |column, h|
      h.values.each do |item|
        list[column][item] = false
      end
    end
    list
  end
end

app/helpers/preparations_helper.rb
module PreparationsHelper
  def flag_td(flag)
    return content_tag('td', class: 'success') if flag
    content_tag('td', class: 'danger')
  end
end

app/views/preparations/_browse.html.slim
h1 進捗報告ページ
- if @preparation.seminar_session.presenter?(current_user)
  .btn-group
    = link_to '進捗報告', edit_preparation_path, class: 'btn btn-info'
    = link_to '項目編集', edit_preparation_list_path, class: 'btn btn-warning'

table.table.preparation-table
  tr
    th.conpact-cell 文献入手
    td
      table.table
        - @preparation.book.each do |title, flag|
          - if flag
            tr.success.conpact-cell
              td = '完 ' + title
          - else
            tr.warning.conpact-cell
              td = '未 ' + title
  tr
    th.conpact-cell 精読
    td
      table.table
        - @preparation.read.each do |part, flag|
          - if flag
            tr.success.conpact-cell
              td = '完 ' + part
          - else
            tr.warning.conpact-cell
              td = '未 ' + part
  tr
    th.conpact-cell ノート作成
    td
      table.table
        - @preparation.note.each do |part, flag|
          - if flag
            tr.success.conpact-cell
              td = '完 ' + part
          - else
            tr.warning.conpact-cell
              td = '未 ' + part
  tr
    th.conpact-cell 資料作成
    td
      table.table
        - @preparation.material.each do |part, flag|
          - if flag
            tr.success.conpact-cell
              td = '完 ' + part
          - else
            tr.warning.conpact-cell
              td = '未 ' + part
        - unless @preparation.seminar_session.resume.blank?
          tr
            td
              = link_to '資料ダウンロード', seminar_session_download_path(id: @preparation.seminar_session.id, type: 'resume')
  tr
    th.conpact-cell 練習
    - if @preparation.practice == 0
      td.warning = @preparation.practice
    - else
      td.success = @preparation.practice

app/views/preparations/_report.html.slim
h1 進捗報告ページ

= form_tag preparation_path, method: :put do
  table.table.preparation-table
    tr
      th.conpact-cell 文献入手
      td
        table
          - @preparation.book.each do |title, flag|
            tr
              td
                label = check_box('book', "#{title}", {checked: flag}, true, false) + ' ' + title
    tr
      th.conpact-cell 精読
      td
        table
          - @preparation.read.each do |part, flag|
            tr
              td
                label = check_box('read', "#{part}", {checked: flag}, true, false) + ' ' + part
    tr
      th.conpact-cell ノート作成
      td
        table
          - @preparation.note.each do |part, flag|
            tr
              td
                label = check_box('note', "#{part}", {checked: flag}, true, false) + ' ' + part
    tr
      th.conpact-cell 資料作成
      td
        table
          - @preparation.material.each do |part, flag|
            tr
              td
                label = check_box('material', "#{part}", {checked: flag}, true, false) + ' ' + part
    tr
      th 発表練習
      td
        = number_field :preparation, :practice
  = submit_tag '報告する', class: 'btn btn-primary'
  = " "
  button.btn.btn-danger 行き詰まり報告

app/views/preparations/edit.html.slim
= link_to '戻る', preparation_path(@preparation)
= render 'report'
= link_to '戻る', preparation_path(@preparation)

app/views/preparations/edit_list.html.slim
= link_to '戻る', preparation_path(@preparation)

h1 準備項目編集

= form_tag update_preparation_list_path do
  table.table.preparation-table
    tr
      th.conpact-cell 文献入手
      td#book
        - @preparation.book.keys.each.with_index(1) do |title, i|
          div
            input[type="text" value="#{title}" name="book[#{i}]"]
            p.btn.delete-btn = glyph(:minus)
        a.btn.add-btn =glyph(:plus)
    tr
      th.conpact-cell 精読
      td#read
        - @preparation.read.keys.each.with_index(1) do |part, i|
          div
            input[type="text", value="#{part}" name="read[#{i}]"]
            p.btn.delete-btn = glyph(:minus)
        a.btn.add-btn =glyph(:plus)
    tr
      th.conpact-cell ノート作成
      td#note
        - @preparation.note.keys.each.with_index(1) do |part, i|
          div
            input[type="text", value="#{part}" name="note[#{i}]"]
            p.btn.delete-btn = glyph(:minus)
        a.btn.add-btn =glyph(:plus)
    tr
      th.conpact-cell 資料作成
      td#material
        - @preparation.material.keys.each.with_index(1) do |part, i|
          div
            input[type="text", value="#{part}" name="material[#{i}]"]
            p.btn.delete-btn#sample = glyph(:minus)
        a.btn.add-btn =glyph(:plus)
  = submit_tag '報告する', class: 'btn btn-primary'


= link_to '戻る', preparation_path(@preparation)

javascript:
  $('.add-btn').on('click', function(){
    var id = $(this).parent().get(0).id;
    var count = $('#'+id).children('div').children('input').length + 1
    var input = $('<input>').attr('type', 'text').attr('name', id + '[' + count + ']')
    var delBtn = $('<p>').addClass('btn delete-btn')
    var delIcon = $('<span>').addClass('glyphicon glyphicon-minus')
    $('#' + id + ' > div:last').after($('<div>'))
    $('#' + id + ' > div:last').append(input)
    $('#' + id + ' > div:last').append(delBtn.append(delIcon))
  });
  $('body').on('click', '.delete-btn', function(){
    if ( $('input', $(this).parent().parent()).length > 1 ) {
      $(this).parent().remove()
    }
  });

app/views/preparations/show.html.slim
= link_to '戻る', seminar_project_path(id: @preparation.seminar_session.seminar_project.id)
= render 'browse'
= link_to '戻る', seminar_project_path(id: @preparation.seminar_session.seminar_project.id)