config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  devise_for :users
  resources :seminar_projects do
    member do
      post :determine
    end
  end
  resources :entries, only: %i(create destroy)
  resources :comments, only: %i(create destroy)
  resources :seminar_sessions
  resources :preparations
  get 'seminar_sessions/:id/download/:type' => 'seminar_sessions#download', as: 'seminar_session_download'
  get 'preparations/:id/list/' => 'preparations#edit_list', as: 'edit_preparation_list'
  post 'preparations/:id/list/' => 'preparations#update_list', as: 'update_preparation_list'
end

app/models/seminar_project.rb
# == Schema Information
#
# Table name: seminar_projects
#
#  id             :integer          not null, primary key
#  title          :text
#  description    :text
#  target         :text
#  genre          :text
#  project_status :integer          default(0), not null
#  data_status    :integer          default(0), not null
#  user_id        :integer          not null
#  promotion      :text
#  created_at     :datetime
#  updated_at     :datetime
#

class SeminarProject < ActiveRecord::Base
  has_many :seminar_project_books, dependent: :destroy
  has_many :books, through: :seminar_project_books
  belongs_to :owner, foreign_key: :user_id, class_name: 'User'
  has_many :entries
  has_many :participants, through: :entries, source: :user
  has_many :seminar_sessions

  scope :is_initiate, -> { where(project_status: ProjectStatus::INITIATE) }
  scope :is_plan, -> { where(project_status: ProjectStatus::PLANNING) }

  module ProjectStatus
    INITIATE = 0
    PLANNING = 100
  end

  def initiate?
    return true if project_status == ProjectStatus::INITIATE
    false
  end

  def planning?
    return true if project_status == ProjectStatus::PLANNING
    false
  end

  def owner?(user)
    return true if user == owner
    false
  end

  def first_book=(book)
    first_book = seminar_project_books.first
    if first_book
      first_book.book_id = book.id
    else
      first_book = SeminarProjectBook.new(book_id: book.id, seminar_project_id: id)
      first_book.relation_type = SeminarProjectBook::RelationType::MAIN
    end
    first_book.save!
  end

  def determine_with_session(time)
    time.times do
      seminar_sessions.create
    end
  end

  def comments
    Comment.where(target: Comment::Target::PROJECT, target_id: id)
  end
end

app/controllers/seminar_projects_controller.rb
class SeminarProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_seminar_project
  before_action :authenticate_owner, only: [:edit, :update]

  def index
  end

  def new
    @seminar_project = SeminarProject.new
  end

  def create
    current_user_id = current_user.id
    seminar_project = SeminarProject.create!(seminar_project_params.merge user_id: current_user_id)
    seminar_project.first_book = find_or_create_book(params[:isbn], params[:book_name])

    Entry.create!(
      seminar_project: seminar_project,
      user_id: current_user_id,
      entry_type: Entry::EntryType::PARTICIPATE
    )

    redirect_to seminar_project_path(seminar_project), alert: { notice: 'create new seminar project' }
  end

  def show
    @entry = current_user.entries.where(seminar_project_id: @seminar_project.id).first
    @project_comment = Comment.new(user_id: current_user.id, target: Comment::Target::PROJECT, target_id: @seminar_project.id)
    @session_comment = Comment.new(user_id: current_user.id, target: Comment::Target::SESSION)
  end

  def edit
    redirect_to root_path unless @seminar_project
  end

  def update
    redirect_to root_path unless @seminar_project
    @seminar_project.update_attributes(seminar_project_params)

    book = find_or_create_book(params[:isbn], params[:book_name])
    @seminar_project.first_book = book

    redirect_to seminar_project_path(@seminar_project)
  end

  def determine
    @seminar_project.project_status = SeminarProject::ProjectStatus::PLANNING
    @seminar_project.save!
    @seminar_project.determine_with_session(params['seminar_session']['number'].to_i)
    redirect_to seminar_project_path(@seminar_project), notice: 'プロジェクトを確定しました'
  end

  private

  def seminar_project_params
    params.require(:seminar_project).permit(:title, :description, :target, :genre, :promotion)
  end

  def find_or_create_book(isbn, book_name)
    book = Book.where(isbn: isbn).first
    unless book
      book = Book.new(isbn: isbn, name: book_name)
      book.save!
    end
    book
  end

  def load_seminar_project
    @seminar_project = SeminarProject.find(params[:id]) unless params[:id].blank?
  end

  def authenticate_owner
    return unless @seminar_project
    @seminar_project = nil unless @seminar_project.user_id == current_user.id
  end
end

app/helpers/seminar_projects_helper.rb
module SeminarProjectsHelper
end

app/views/seminar_projects/_change_modal.html.slim
= form_tag determine_seminar_project_path(@seminar_project) do
  - modal_body = capture do
    .form-group
      = label :seminar_session, :number, '予定セッション数'
      = number_field :seminar_session, :number
  = modal_dialog id: 'chModal',
    header: {show_close: true, title: '輪講プロジェクト確定'},
    body: modal_body,
    footer: submit_tag('確定する', class: "btn btn-primary") + content_tag(:button, 'キャンセル', 'data-dismiss' => 'modal', class: "btn btn-default")

app/views/seminar_projects/_form.html.slim
= form_for seminar_project do |f|
  .form-group
    = f.label :title, '輪講プロジェクトのタイトル'
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :description, 'プロジェクト概要'
    = f.text_area :description, class: "form-control"
  .form-group
    = f.label :isbn, '書籍のISBN'
    = text_field_tag :isbn, seminar_project.decorate.isbn, class: "form-control"
  .form-group
    = f.label :book_name, '書籍名'
    = text_field_tag :book_name,seminar_project.decorate.book_name(empty: true), class: "form-control"
  .form-group
    = f.label :target, '対象者'
    = f.text_field :target, class: "form-control"
  .form-group
    = f.label :genre, 'ジャンル'
    = f.text_field :genre, class: "form-control"
  .form-group
    = f.label :promotion, '勧誘コメント'
    = f.text_area :promotion, class: "form-control"
  - if seminar_project.persisted?
    = f.submit "更新", class: 'btn btn-primary'
  - else
    = f.submit "作成", class: 'btn btn-primary'

app/views/seminar_projects/_project.html.slim
h1 輪講プロジェクト詳細

- if @seminar_project.owner?(current_user)
  .btn-group
    = link_to glyph(:pencil)+" 編集", edit_seminar_project_path(@seminar_project), class: "btn btn-warning"
    - if @seminar_project.project_status == SeminarProject::ProjectStatus::INITIATE
      = modal_toggle '確定', dialog: '#chModal', class: "btn btn-primary"
  = render 'change_modal'
- else
  - if current_user.participant?(@seminar_project)
    = link_to '参加をやめる', entry_path(seminar_project_id: @seminar_project), class: "btn btn-danger", method: :delete
  - elsif current_user.thinking?(@seminar_project)
    .btn-group
      = link_to '参加する', entries_path(seminar_project_id: @seminar_project.id, entry_type: Entry::EntryType::PARTICIPATE), class: "btn btn-info", method: :post
      = link_to '検討をやめる', entry_path(seminar_project_id: @seminar_project), class: "btn btn-danger", method: :delete
  - else
    .btn-group
      = link_to '参加する', entries_path(seminar_project_id: @seminar_project.id, entry_type: Entry::EntryType::PARTICIPATE), class: "btn btn-info", method: :post
      = link_to '検討する', entries_path(seminar_project_id: @seminar_project.id, entry_type: Entry::EntryType::THINKING), class: "btn btn-primary", method: :post

table.table.table-striped
  tr
    th タイトル
    td = @seminar_project.title
  tr
    th 主催者
    td = @seminar_project.owner.decorate.name
  tr
    th 対象書籍
    td = @seminar_project.decorate.book_name
  tr
    th 概要
    td = raw(@seminar_project.decorate.description)
  tr
    th 対象者
    td = @seminar_project.target
  tr
    th ジャンル
    td = @seminar_project.genre
  tr
    th 勧誘コメント
    td = @seminar_project.promotion
.row
  .col-md-6
    .panel.panel-info
      .panel-heading 参加者
      .panel-body
        table.table
            - @seminar_project.entries.is_participant.includes(:user).each do |u|
              tr
                td.conpact-cell = u.user.real_name
                td = u.user.student_code
  .col-md-6
    .panel.panel-primary
      .panel-heading 検討者
      .panel-body
        table.table
          tr
            - @seminar_project.entries.is_thinking.includes(:user).each do |u|
              tr
                td.conpact-cell = u.user.real_name
                td = u.user.student_code
.panel.panel-default
  .panel-heading コメント
  .panel-body
    = form_for @project_comment, html: { class: "form-inline" } do |f|
      = f.hidden_field :target, value: Comment::Target::PROJECT
      = f.hidden_field :target_id, value: @seminar_project.id
      .form-group
        = f.text_field :content, class: "form-control comment-form"
      = f.submit "投稿", class: "btn btn-default"
    table.table
      - @seminar_project.comments.each do |c|
        tr
          th.conpact-cell = c.user.nick_name + " >"
          td = c.content

app/views/seminar_projects/edit.html.slim
= render 'form', seminar_project: @seminar_project

app/views/seminar_projects/new.html.slim
h1 輪講プロジェクト発議

= render 'form', seminar_project: @seminar_project

app/views/seminar_projects/show.html.slim
h1 プロジェクト詳細
- if @seminar_project.initiate?
  = render 'project'
- else
  ul.nav.nav-tabs[role="tablist"]
    li
      a[href="#project" aria-controls="project" role="tab" data-toggle="tab"]
        | Project
    li
      a[href="#sessions" aria-controls="sessions" role="tab" data-toggle="tab"]
        | Sessions
  .tab-content
    .tab-pane#project
      = render 'project'
    .tab-pane#sessions
      = render 'seminar_sessions/list'

coffee:
  $ ->
  $('.nav-tabs a:first').click()